export const content = [
    {
        id: '1',
        icon: '../assets/img/user-icon.png',
        first_name: 'David',
        last_name: 'Rowland',
        top: '1',
        points: '350',
        work_days: '15',
        time_total_average: '09:29:53',
        time_total_summary: '127:29:14',
        time_work_average: '07:29:53',
        time_work_summary: '28:29:14',
        time_break_average: '06:29:53',
        time_break_summary: '22:29:14',
        delays_count: 2
    },
    {
        id: '2',
        icon: '../assets/img/user-icon.png',
        first_name: 'Rhianon',
        last_name: 'Greer',
        top: '2',
        points: '300',
        work_days: '14',
        time_total_average: '09:29:53',
        time_total_summary: '127:29:14',
        time_work_average: '07:29:53',
        time_work_summary: '28:29:14',
        time_break_average: '06:29:53',
        time_break_summary: '22:29:14',
        delays_count: 0
    },
    {
        id: '3',
        icon: '../assets/img/user-icon.png',
        first_name: 'Maile',
        last_name: 'Salas',
        top: '3',
        points: '250',
        work_days: '13',
        time_total_average: '09:29:53',
        time_total_summary: '127:29:14',
        time_work_average: '07:29:53',
        time_work_summary: '28:29:14',
        time_break_average: '06:29:53',
        time_break_summary: '22:29:14',
        delays_count: 0
    },
    {
        id: '4',
        icon: '../assets/img/user-icon.png',
        first_name: 'Coby',
        last_name: 'Levy',
        top: '4',
        points: '200',
        work_days: '17',
        time_total_average: '09:29:53',
        time_total_summary: '127:29:14',
        time_work_average: '07:29:53',
        time_work_summary: '28:29:14',
        time_break_average: '06:29:53',
        time_break_summary: '22:29:14',
        delays_count: 7
    },
    {
        id: '5',
        icon: '../assets/img/user-icon.png',
        first_name: 'Iris',
        last_name: 'Foreman',
        top: '5',
        points: '150',
        work_days: '14',
        time_total_average: '09:29:53',
        time_total_summary: '127:29:14',
        time_work_average: '07:29:53',
        time_work_summary: '28:29:14',
        time_break_average: '06:29:53',
        time_break_summary: '22:29:14',
        delays_count: 0
    },
    {
        id: '6',
        icon: '../assets/img/user-icon.png',
        first_name: 'Denton',
        last_name: 'Le',
        top: '6',
        points: '100',
        work_days: '15',
        time_total_average: '09:29:53',
        time_total_summary: '127:29:14',
        time_work_average: '07:29:53',
        time_work_summary: '28:29:14',
        time_break_average: '06:29:53',
        time_break_summary: '22:29:14',
        delays_count: 1
    },
    {
        id: '7',
        icon: '../assets/img/user-icon.png',
        first_name: 'Mason',
        last_name: 'Owen',
        top: '7',
        points: '50',
        work_days: '9',
        time_total_average: '09:29:53',
        time_total_summary: '127:29:14',
        time_work_average: '07:29:53',
        time_work_summary: '28:29:14',
        time_break_average: '06:29:53',
        time_break_summary: '22:29:14',
        delays_count: 0
    },
    {
        id: '8',
        icon: '../assets/img/user-icon.png',
        first_name: 'Alden',
        last_name: 'Nunez',
        top: '8',
        points: '40',
        work_days: '20',
        time_total_average: '09:29:53',
        time_total_summary: '127:29:14',
        time_work_average: '07:29:53',
        time_work_summary: '28:29:14',
        time_break_average: '06:29:53',
        time_break_summary: '22:29:14',
        delays_count: 3
    },
    {
        id: '9',
        icon: '../assets/img/user-icon.png',
        first_name: 'Jeremy',
        last_name: 'Mann',
        top: '9',
        points: '30',
        work_days: '11',
        time_total_average: '09:29:53',
        time_total_summary: '127:29:14',
        time_work_average: '07:29:53',
        time_work_summary: '28:29:14',
        time_break_average: '06:29:53',
        time_break_summary: '22:29:14',
        delays_count: 1
    }
];
